#!/usr/bin/env node
const fs = require("fs");
const os = require("os");
const path = require("path");

const ROOT = process.cwd();
const HOME = os.homedir();
const COPILOT_DIR = path.join(HOME, ".copilot");
const GITHUB_DIR = path.join(ROOT, ".github");
const dryRun = process.argv.includes("--dry-run");

function exists(p) {
  return fs.existsSync(p);
}

function walkFiles(dir, acc = []) {
  if (!exists(dir)) return acc;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walkFiles(full, acc);
    else acc.push(full);
  }
  return acc;
}

function relTo(base, p) {
  return path.relative(base, p);
}

function removeFileIfExists(p) {
  if (!exists(p)) return false;
  if (dryRun) {
    console.log(`[dry-run] remove file ${p}`);
    return true;
  }
  fs.unlinkSync(p);
  console.log(`removed file ${p}`);
  return true;
}

function removeDirIfEmpty(p) {
  if (!exists(p) || !fs.statSync(p).isDirectory()) return false;
  const entries = fs.readdirSync(p);
  if (entries.length !== 0) return false;
  if (dryRun) {
    console.log(`[dry-run] remove empty dir ${p}`);
    return true;
  }
  fs.rmdirSync(p);
  console.log(`removed empty dir ${p}`);
  return true;
}

function removeDirTreeIfExists(p) {
  if (!exists(p) || !fs.statSync(p).isDirectory()) return false;
  if (dryRun) {
    console.log(`[dry-run] remove dir tree ${p}`);
    return true;
  }
  fs.rmSync(p, { recursive: true, force: true });
  console.log(`removed dir tree ${p}`);
  return true;
}

function cleanupEmptyParents(startDir, stopDir) {
  let current = startDir;
  const stop = path.resolve(stopDir);
  while (path.resolve(current).startsWith(stop) && path.resolve(current) !== stop) {
    if (!removeDirIfEmpty(current)) break;
    current = path.dirname(current);
  }
}

function mapSetupInstalledFiles() {
  const files = new Set();

  // Global installs to ~/.copilot
  for (const src of walkFiles(path.join(ROOT, "memory"))) {
    files.add(path.join(COPILOT_DIR, "memory", relTo(path.join(ROOT, "memory"), src)));
  }
  for (const src of walkFiles(path.join(ROOT, "learning"))) {
    files.add(path.join(COPILOT_DIR, "learning", relTo(path.join(ROOT, "learning"), src)));
  }
  const skillsRoot = path.join(ROOT, "skills");
  if (exists(skillsRoot)) {
    for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const skillMd = path.join(skillsRoot, entry.name, "SKILL.md");
      if (exists(skillMd)) files.add(path.join(COPILOT_DIR, "skills", `${entry.name}.md`));
    }
  }
  files.add(path.join(COPILOT_DIR, "mcp.json"));
  for (const src of walkFiles(path.join(ROOT, "skills", "pptx-agent", "scripts"))) {
    files.add(path.join(COPILOT_DIR, "pptx", relTo(path.join(ROOT, "skills", "pptx-agent", "scripts"), src)));
  }
  files.add(path.join(COPILOT_DIR, "copilot-instructions.md"));
  files.add(path.join(HOME, "AGENTS.md"));
  files.add(path.join(COPILOT_DIR, "agent_boot.py"));

  // Project installs to .github
  const agentsRoot = path.join(ROOT, "agents");
  if (exists(agentsRoot)) {
    for (const role of fs.readdirSync(agentsRoot, { withFileTypes: true })) {
      if (!role.isDirectory()) continue;
      const roleDir = path.join(agentsRoot, role.name);
      for (const agent of fs.readdirSync(roleDir, { withFileTypes: true })) {
        if (!agent.isDirectory()) continue;
        const agentFile = path.join(roleDir, agent.name, `${agent.name}.agent.md`);
        if (exists(agentFile)) {
          files.add(path.join(GITHUB_DIR, "agents", `${role.name}-${agent.name}.agent.md`));
        }
      }
    }
  }

  for (const src of walkFiles(path.join(ROOT, "skills"))) {
    files.add(path.join(GITHUB_DIR, "skills", relTo(path.join(ROOT, "skills"), src)));
  }

  for (const comp of ["security", "instructions", "prompts", "chatmodes", "memory"]) {
    const compRoot = path.join(ROOT, comp);
    for (const src of walkFiles(compRoot)) {
      files.add(path.join(GITHUB_DIR, comp, relTo(compRoot, src)));
    }
  }

  return [...files];
}

function main() {
  if (!exists(path.join(ROOT, "package.json")) || !exists(path.join(ROOT, "setup.js"))) {
    console.error("Run this script from repository root where setup.js exists.");
    process.exit(1);
  }

  const targets = mapSetupInstalledFiles();
  let removed = 0;

  for (const target of targets) {
    if (removeFileIfExists(target)) {
      removed += 1;
      cleanupEmptyParents(path.dirname(target), COPILOT_DIR);
      cleanupEmptyParents(path.dirname(target), GITHUB_DIR);
    }
  }

  const catalogPath = path.join(GITHUB_DIR, "agent-catalog.json");
  if (removeFileIfExists(catalogPath)) {
    removed += 1;
  }

  // These project-level folders are fully generated by setup.js, so stale
  // content is safer to remove as a whole tree than file-by-file.
  for (const d of [path.join(GITHUB_DIR, "agents"), path.join(GITHUB_DIR, "skills")]) {
    if (removeDirTreeIfExists(d)) {
      removed += 1;
    }
  }

  // Best-effort top-level empty dirs cleanup
  for (const d of [
    path.join(COPILOT_DIR, "memory"),
    path.join(COPILOT_DIR, "learning"),
    path.join(COPILOT_DIR, "skills"),
    path.join(COPILOT_DIR, "pptx"),
    path.join(GITHUB_DIR, "agents"),
    path.join(GITHUB_DIR, "skills"),
    path.join(GITHUB_DIR, "security"),
    path.join(GITHUB_DIR, "instructions"),
    path.join(GITHUB_DIR, "prompts"),
    path.join(GITHUB_DIR, "chatmodes"),
    path.join(GITHUB_DIR, "memory"),
  ]) {
    removeDirIfEmpty(d);
  }

  console.log(
    dryRun
      ? `Dry run complete. ${removed} setup-managed item(s) would be removed.`
      : `Cleanup complete. ${removed} setup-managed item(s) removed.`
  );
}

main();
